// <auto-generated />
namespace CatalogModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_piping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_piping));
        
        string IMigrationMetadata.Id
        {
            get { return "201706160742156_update_piping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
